[Logger]
FilePath = ""
LogLevel = "DEBUG"

[Service]
Host = "0.0.0.0"
Port = 8080
Domain = "localhost"
Schema = "http"
CertFile = "xxxxx"
KeyFile = "xxxxx"

[Jwt]
SigKey = "xxxxx"
ExpireTime = 60

[Database]
[Database.Mysql]
Host = "127.0.0.1"
Port = 3306
Username = "root"
Password = "123456"
DBName = "db_iris"
[Database.Redis]
Host = "127.0.0.1"
Port = 6379
Password = ""
DB = 0

[Custom]
Name = "kainhuck"
Age = 18