[Logger]
FilePath = ""
LogLevel = "DEBUG"

[Service]
Host = "0.0.0.0"
Port = 8080

[Jwt]
SigKey = "xxxxx"
ExpireTime = 60

[Database]
[Database.Mysql]
Host = "127.0.0.1"
Port = 3306
Username = "root"
Password = "123456"
DBName = "db_iris"

[Custom]
Name = "kainhuck"
Age = 18